/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_HONO_SERVER: string
  readonly VITE_ZERO_SERVER: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}